name: unwanted runs cleaning workflow
on: 
  workflow_dispatch
jobs:
  clreanruns:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: dmvict/clean-workflow-runs@v1.0.0
        with:
          token: ${{ secrets.PRIVATE_GITHUB_TOKEN }}
          repo: prakuldip/ninowebappcicd
          branch: main
          workflow_id: cleanruns.yml
          run_conclusions: |
            failure
            skipped
            cancelled
          save_period: 0
          save_min_runs_number: 0
      
    
