name: webappdeployment 👨‍🚀

on: 
    workflow_dispatch

env: 
    AZURE_WEBAPP_NAME: current-time-service
    AZURE_WEBAPP_PACKAGE_PATH: "./publish"

jobs: 
    publish:
        runs-on: ubuntu-latest
    
        steps:
            - uses: actions/checkout@v4

            - name: Set up .NET
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: '6.0.x'
            
            - name: Restore
              run: dotnet restore ./CurrentTimeService.sln

            - name: Build
              run: dotnet build ./CurrentTimeService.sln --configuration Release --no-restore

            - name: Publish
              run: dotnet publish ./CurrentTimeService.sln --configuration Release --no-build --output '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'

            - name: displayvariables
              run: |
                echo $AZURE_WEBAPP_NAME
                echo $AZURE_WEBAPP_PACKAGE_PATH
                pwd
                echo $GITHUB_WORKSPACE

            - name: deploy to web app
              uses: azure/webapps-deploy@v2
              with:
                app-name: ${{ env.AZURE_WEBAPP_NAME }}
                publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
                package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

            


